export const PASS_GEN_TXT = {
  ENG: {
    TITLE: "Password Generator",
    DESC: "Select your options, then click 'Create Password' to generate your password.",
    LOWERCASE: "Lowercase",
    UPPERCASE: "Uppercase",
    NUMBERS: "Numbers",
    SYMBOLS: "Symbols",
    MIN_NUMS: "Minimum Amount of Numbers",
    MIN_SYMS: "Minimum Amount of Symbols",
    PASS_LEN: "Password Length",
    WAITING: "",
    CREATE_PASS: "Create Password",
    COPY_PASS: "Copy Password",
    COPY_ALERT: "Your password has been copied!",
    ERR_LEN: "Invalid length: increase your minimum values or password length.",
    ERR_OPT: "Please choose at least one option.",
  },
  JP: {
    TITLE: "パスワード自動生成アプリ",
    DESC: "最初はオプションを選択し、そして「パスワードを作成する」というボタンを押してパスワードを作りましょう。",
    LOWERCASE: "小文字",
    UPPERCASE: "大文字",
    NUMBERS: "数字",
    SYMBOLS: "記号",
    MIN_NUMS: "数字の最小限",
    MIN_SYMS: "記号の最小限",
    PASS_LEN: "パスワードの長さ",
    WAITING: "",
    CREATE_PASS: "パスワードを作成する",
    COPY_PASS: "パスワードをコピーする",
    COPY_ALERT: "パスワードは無事にコピーされました！",
    ERR_LEN: "長さ又は最小限を上げてください。",
    ERR_OPT: "上記の選択肢を少なくとも１つお選びください。",
  },
};
