export const SIDEBAR_TXT = {
  ENG: {
    HOME: {
      NAME: "Home",
      DESC: "You can view this site's source code at the Github link below.  Also, you can see the source code for each page by following each page's code link.",
      CODE_TEXT: "Website Code - Github",
    },

    SUDOKU: {
      NAME: "Sudoku Solver",
      DESC: "A sudoku solver which uses recursion and backtracking to find the solution.  Sudokus are generated by calling a public API using Axios.",
      CODE_TEXT: "Sudoku Code - Github",
      COMP_TEXT: "Sudoku Form Component - Github",
    },

    PASS_GEN: {
      NAME: "Password Generator",
      DESC: "A password generator which generates a random password based on user input, including which character sets to include, minimum amounts of numbers and symbols, and password length.",
      CODE_TEXT: "Password Logic - Github",
      COMP_TEXT: "Password Form Component - Github",
    },
  },

  JP: {
    HOME: {
      NAME: "ホームページ",
      DESC: "本サイトのソースコードは以下のリンクを押せばご覧になります。また、各ページのコードリンクを押せば、そのページのソースコードが見えます。",
      CODE_TEXT: "本サイトのソースコード・Github",
    },
    SUDOKU: {
      NAME: "数独自動解決アプリ",
      DESC: "再帰のアルゴリズムにより、数独を自動的に解決するアプリ。数独はAxiosというモジュールを利用してAPIから読みます。",
      CODE_TEXT: "数独自動解決アプリのソースコード・Github",
      COMP_TEXT: "数独のReactコンポーネント・Github",
    },
    PASS_GEN: {
      NAME: "パスワード自動生成アプリ",
      DESC: "ユーザーの記入した情報に基づいて自動的にパスワードを作成するアプリ。",
      CODE_TEXT: "パスワードアプリのソースコード・Github",
      COMP_TEXT: "パスワードアプリのReactコンポーネント・Github",
    },
  },
};
